import './components/theme-switcher'
import './components/password-toggle'
import './components/select'
import './components/section-slider'
import './components/footer'
import './components/header'
import './components/section-donor-code'
import './components/tabs'